### ISSUE TITLE
Android O prevents background execution of broadcast

### ISSUE THREAD

**Issue by AfzalivE** [AfzalivE/AwakeDebug#3]
```
09-26 12:58:01.924 915-2424/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_CONNECTED flg=0x4000010 (has extras) } to com.afzaln.awakedebug/.PowerConnectionReceiver
09-26 12:58:26.691 2112-2120/com.afzaln.awakedebug I/zygote64: Debugger is no longer active
09-26 12:58:26.826 915-31746/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_DISCONNECTED flg=0x4000010 (has extras) } to com.afzaln.awakedebug/.PowerConnectionReceiver
09-26 12:58:29.582 915-1548/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_CONNECTED flg=0x4000010 (has extras) } to com.afzaln.awakedebug/.PowerConnectionReceiver

```

**Comment by AfzalivE** [comment]
Seems like this is gonna be impossible without a background service in Android O.

Using a job scheduler can allow near-immediate detection of plugging in but not plugging out :/ WTF google

**Comment by AfzalivE** [comment]
Well, for now, this means back to target SDK 25

**Comment by dhavaljardosh** [comment]
Any luck?

**Comment by AfzalivE** [comment]
Nope but it works in oreo with the older target SDK (25) :p
  
https://commonsware.com/blog/2017/04/11/android-o-implicit-broadcast-ban.html

Look under workarounds.

> If you are receiving system-sent implicit broadcasts (e.g., ACTION_PACKAGE_ADDED), keep your targetSdkVersion at 25 or lower, until we figure out better workarounds that (hopefully) do not involve polling.

**Comment by dhavaljardosh** [comment]
Yeah, I read and tried that. But didn't work.
Will research and attempt in the evening when I reach home, and will let you know. Thank you very much.

**Comment by AfzalivE** [comment]
Yeah do let me know if you find something. Which broadcast are you looking for?

**Comment by AfzalivE** [comment]
Due to this, this app might just stop receiving updates from Nov 2018, unless there's a fix for targetSdkVersion 26

https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

**Comment by AfzalivE** [comment]
I can think of one workaround but it'll most probably require an ongoing notification.

JobScheduler (`setRequiresCharging` has issues where it might not work in common cases) -> Keep a foreground service that registers a receiver for the `ACTION_POWER_DISCONNECTED` broadcast -> shutdown service.

I haven't tried and I am a bit hesitant to try this at the moment
